algoritmo "CYBER PROFILE CLI"
var
   nome: caractere
   trilha: caractere
   aulas_concluidas: inteiro
   horas_estudadas: real
   laboratorio_configurado: logico
   projeto_atual: caractere

inicio
   nome <- "João"
   trilha <- "Fundamentos da Cibersegurança"
   aulas_concluidas <- 2
   horas_estudadas <- 4.5
   laboratorio_configurado <- verdadeiro
   projeto_atual <- "CyberLogic Lab"

   escreval("================================")
   escreval("        CYBER PROFILE CLI       ")
   escreval("================================")
   escreval("Nome: ", nome)
   escreval("Trilha: ", trilha)
   escreval("Aulas concluídas: ", aulas_concluidas)
   escreval("Horas estudadas: ", horas_estudadas)
   escreval("Laboratório configurado: ", laboratorio_configurado)
   escreval("Projeto atual: ", projeto_atual)
fimalgoritmo
